# Generated by Django 4.2 on 2024-01-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Фото')),
                ('vk', models.URLField(blank=True, default='', verbose_name='Вконтакте')),
                ('wa', models.URLField(blank=True, default='', verbose_name='WhatsApp')),
                ('tg', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('portfolio_favorites', models.ManyToManyField(blank=True, max_length=20, related_name='portfolio_favorites_users', to='api.portfolio', verbose_name='Избранные портфолио')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
