# Generated by Django 4.2 on 2023-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_link_user_portfolio_favorites_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AddField(
            model_name='link',
            name='tg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='vk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='wa',
            field=models.TextField(blank=True, default=''),
        ),
    ]
