# Generated by Django 4.2.7 on 2024-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolio_user_profile_user_alter_profile_tg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg',
            field=models.URLField(blank=True, default='', verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk',
            field=models.URLField(blank=True, default='', verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wa',
            field=models.URLField(blank=True, default='', verbose_name='WhatsApp'),
        ),
    ]
