# Generated by Django 4.2 on 2023-11-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_link_options_link_tg_link_vk_link_wa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='link',
        ),
        migrations.AddField(
            model_name='user',
            name='tg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='wa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
