# Generated by Django 4.2.7 on 2024-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_portfolio_image_portfolioimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wa',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
