# Generated by Django 4.2.7 on 2024-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_wa'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата реализации'),
        ),
    ]
