# Generated by Django 4.2 on 2023-11-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='portfolio_favorites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wa',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Местоположение человека - Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_favorites',
            field=models.ManyToManyField(blank=True, max_length=20, related_name='portfolio_favorites_users', to='api.portfolio', verbose_name='Избранные портфолио'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='wa',
            field=models.TextField(blank=True, default=''),
        ),
    ]
