# Generated by Django 4.2.7 on 2024-02-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_portfolio_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telegram'),
        ),
    ]
