# Generated by Django 4.2.7 on 2024-02-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_portfolio_date_work_alter_portfolio_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации проекта'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_work',
            field=models.DateField(blank=True, null=True, verbose_name='Дата реализации'),
        ),
    ]
