# Generated by Django 4.2.7 on 2024-02-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_playlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Плейлист проектов', 'verbose_name_plural': 'Плейлисты проектов'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Описание'),
        ),
    ]
