# Generated by Django 4.2.7 on 2024-02-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_alter_playlist_options_alter_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='date',
            new_name='created_at',
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Контактная почта')),
                ('description', models.TextField(blank=True, max_length=600, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата отправки заявки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связаться с нами',
                'verbose_name_plural': 'Связаться с нами',
            },
        ),
    ]
