# Generated by Django 4.2.7 on 2024-02-26 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_portfolioimage_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.portfolio'),
        ),
    ]
