# Generated by Django 4.2.7 on 2024-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_portfolioimage_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации проекта'),
        ),
    ]
