# Generated by Django 4.2.7 on 2024-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_portfolio_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации проекта'),
        ),
    ]
