# Generated by Django 4.2.7 on 2024-01-14 13:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True, verbose_name='моб. телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(default='', max_length=255, verbose_name='Профессия'),
        ),
    ]
