# Generated by Django 4.2.7 on 2024-02-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_mobile_alter_customuser_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
