# Generated by Django 4.2.7 on 2024-02-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_password_reset_token_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
    ]
